version: '3.3'
services:
  lists_orch:
    image: lists_orch
    depends_on:
     - redis
     - mysql
    networks:
     - lists_network

  redis:
    image: redis:latest
    restart: always
    networks:
     - lists_network

  mysql:
    image: lists_mysql
    restart: always
    networks:
     - lists_network
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=temp

networks:
  lists_network:
    driver: bridge