version: '3.3'
services:
  lists_orch:
    image: lists_orch
    depends_on:
     - redis
     - mysql
    networks:
     - lists_network

  redis:
    image: redis:latest
    restart: always
    networks:
     - lists_network
    ports:
     - "6379:6379"

  mysql:
    image: d0s_mysql:0.1
    restart: always
    networks:
     - lists_network
    ports:
     - "9999:3306"
    expose:
     - "9999"
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=temp
    volumes:
     - mysql_mysqldata:/var/lib/mysql

networks:
  lists_network:
    driver: bridge

volumes:
    mysql_mysqldata: